services:
    speedtest:
        restart: unless-stopped
        container_name: openspeedtest
        ports:
            - '8087:3000'
              #- '3001:3001'
        image: openspeedtest/latest
