scrape_configs:
  - job_name: 'containeradvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.178.100:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.178.100:9100']
