version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    user: "1000"
    volumes:
      - /home/server/docker/tig-stack/volumes/influxdb:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - /home/server/docker/tig-stack/volumes/grafana/varlib/:/var/lib/grafana:rw
      - /home/server/docker/tig-stack/volumes/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
    dns:
      - 9.9.9.9

volumes:
  grafana-storage:
  influxdb-storage:
