version: '2'

services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
    hostname: iobroker
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "1883:1883"
    volumes:
      - /home/server/docker/iobroker/volumes/:/opt/iobroker
    dns:
      - 9.9.9.9
