services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-app
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    env_file:
      - app.env
    volumes:
      -  ~/docker/nginx-proxy-manager/volumes/data/:/data
      -  ~/docker/nginx-proxy-manager/volumes/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-db
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      -  ~/docker/nginx-proxy-manager/volumes/mysql:/var/lib/mysql
